name: CI/CD Pipeline with Docker

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Kód letöltése a GitHub repository-ból
      - name: Checkout code
        uses: actions/checkout@v3
          # Add execute permission to mvnw and list file permissions
                - name: Set execute permission for mvnw
                run: |
                  chmod +x ./mvnw
                  ls -l ./mvnw    # List the file permissions
                  
                  # Maven build
                  - name: Build with Maven
                    run: ./mvnw clean package
      # 2. JDK 17 beállítása a Docker image buildeléséhez (mivel Spring Boot-ot használunk)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Maven build (a JAR fájl létrehozása)
      - name: Build with Maven
        run: ./mvnw clean package

      # 4. Docker image buildelése (mivel a JAR fájl létrejött a target/ mappában)
      - name: Build Docker Image
        run: |
          docker build -t examapp .

      # 5. Docker container futtatása
      - name: Run Docker Container
        run: |
          docker run -d -p 8080:8080 examapp
