name: CI/CD Pipeline with Docker

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Kód letöltése a GitHub repository-ból
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. JDK 17 beállítása a Docker image buildeléséhez
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Maven telepítése (ha szükséges)
      - name: Install Maven
        run: sudo apt-get install -y maven  # Telepíti a Maven-t, ha még nincs telepítve

      # 4. Set execute permission for mvnw and list file permissions
      - name: Set execute permission for mvnw
        run: |
          chmod +x ./mvnw           # Set execute permission
          ls -l ./mvnw              # List the file permissions to ensure it's executable

      # 5. Maven build (a JAR fájl létrehozása)
      - name: Build with Maven
        run: ./mvnw clean package   # Maven használata bash nélkül

      # 6. Docker image buildelése
      - name: Build Docker Image
        run: |
          docker build -t examapp .   # Docker image építése a jelenlegi könyvtárban

      # 7. Docker container futtatása
      - name: Run Docker Container
        run: |
          docker run -d -p 8080:8080 examapp   # Docker konténer elindítása a 8080 porton
