name: CI/CD Pipeline with Docker

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Kód letöltése a GitHub repository-ból
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. JDK 17 beállítása a Docker image buildeléséhez (mivel Spring Boot-ot használunk)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Docker image buildelése
      - name: Build Docker Image
        run: |
          docker build -t examapp .

      # 4. Docker container futtatása
      - name: Run Docker Container
        run: |
          docker run -d -p 8080:8080 examapp
